; PlatformIO Project Configuration File for Seeed Studio XIAO ESP32-C6
; Projekt: KHV

[platformio]
core_dir = C:/.platformio

[env:seeed_xiao_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = seeed_xiao_esp32c6
framework = arduino
monitor_speed = 115200

build_flags = 
    -I"../cred"
